EMPTY               = ""
MSG_FOUND           = "{} found: {}"
MSG_NOT_FOUND       = "{} not found: {}"
MSG_MUST_HAVE       = "{} must be given."
MSG_FILE_EXIST      = "File exists: {}"
MSG_FILE_SAVED      = "File saved: {}"
MSG_FILE_CREATED    = "File created: {}"
MSG_FILE_DOWNLOADED = "File downloaded: {}"
MSG_FILE_OVERWRITEN = "File overwriten: {}"
MSG_FILE_READING_ERROR = "Error reading file: {}"
MSG_CREATION_ERROR  = "Error creating {}: {}"
MSG_CSV_FILE_ERROR  = "Error with csv file: {}"
MSG_REC_COUNT       = "Record count: {}"
MSG_TXT_LENGTH      = "Text length: {}"
MSG_UNIQ_VALUES     = "Uniques: {}"
METHOD_INIT         = "__init__({})"
METHOD_EXEC         = "execute()"
DATE_FORMNAT        = "%Y-%m-%d %H:%M:%S"
EXTRACTOR_MIN_COUNT  = 20
EXTRACTOR_MAX_WORDS  = 400
EXTRACTOR_MAX_LENGTH = 2000
SUMMARISER_MAX_WORDS = 500
TRANSLATOR_MAX_WORDS = 400
TRANSLATOR_DEST      = 'en'
DEFAULT_MULTIPLIER   = 0.7
SUMMARY_TEXT         = 'summary_text'
